# Generated by Django 3.2.9 on 2022-01-03 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('C_id', models.AutoField(primary_key=True, serialize=False)),
                ('C_Name', models.TextField(max_length=30)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Race_Answer',
            fields=[
                ('R_id', models.AutoField(primary_key=True, serialize=False)),
                ('Race_doc', models.TextField(max_length=255)),
                ('Status', models.BooleanField(default=True)),
                ('C_Name', models.TextField(max_length=30)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_api.course')),
            ],
            options={
                'db_table': 'race_answer',
            },
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('Sign_id', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_api.course')),
            ],
            options={
                'db_table': 'sign',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('S_id', models.AutoField(primary_key=True, serialize=False)),
                ('S_Name', models.TextField(max_length=30)),
                ('S_Email', models.TextField(max_length=50)),
                ('S_Password', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('T_id', models.AutoField(primary_key=True, serialize=False)),
                ('T_Name', models.TextField(max_length=30)),
                ('T_Email', models.TextField(max_length=50)),
                ('T_Password', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('Team_id', models.AutoField(primary_key=True, serialize=False)),
                ('Group_number', models.TextField(max_length=50)),
                ('Leader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_api.student')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('TeamMember_id', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('S_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_api.student')),
                ('Team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_api.team')),
            ],
            options={
                'db_table': 'team_member',
            },
        ),
        migrations.CreateModel(
            name='Team_Desc',
            fields=[
                ('TeamDesc_id', models.AutoField(primary_key=True, serialize=False)),
                ('Team_doc', models.TextField(max_length=255)),
                ('Group_Total', models.DecimalField(decimal_places=38, max_digits=38)),
                ('Group_limit', models.DecimalField(decimal_places=38, max_digits=38)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_api.course')),
            ],
            options={
                'db_table': 'team_desc',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='Team_desc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_api.team_desc'),
        ),
        migrations.CreateModel(
            name='Sign_Record',
            fields=[
                ('SR_id', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('S_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_api.student')),
                ('Sign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_api.sign')),
            ],
            options={
                'db_table': 'sign_record',
            },
        ),
        migrations.CreateModel(
            name='Race_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('R_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_api.race_answer')),
                ('S_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_api.student')),
            ],
            options={
                'db_table': 'race_list',
            },
        ),
        migrations.AddField(
            model_name='race_answer',
            name='S_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_api.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='T_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_api.teacher'),
        ),
    ]
