# Generated by Django 3.2.9 on 2022-01-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('T_id', 'T_Email')},
        ),
    ]
