# Generated by Django 3.2.9 on 2022-02-05 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0003_auto_20220204_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Record',
            fields=[
                ('CR_id', models.AutoField(primary_key=True, serialize=False)),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_api.course')),
                ('S_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_api.student')),
            ],
            options={
                'db_table': 'course_record',
            },
        ),
    ]
