# Generated by Django 3.2.9 on 2022-02-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0004_course_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race_answer',
            name='C_Name',
        ),
    ]
