# Generated by Django 3.2.9 on 2022-02-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0005_remove_race_answer_c_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race_answer',
            name='S_id',
        ),
        migrations.AddField(
            model_name='race_list',
            name='Answer',
            field=models.BooleanField(default=True),
        ),
    ]
