# Generated by Django 3.2.9 on 2022-01-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='my title', max_length=30)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
